# NightScout CGM Uzaktan İzlemeyi Kolayca Dağıtın (https://github.com/nightscout/cgm-remote-monitor)
# Render'a tıklayın (https://render.com)
# ------------------------------
# 1. https://github.com/nightscout/cgm-remote-monitor adresini kendi GitHub hesabınıza kopyalayın.
# 2. Forked deponuzun köküne bir render.yaml dosyası ekleyin, aşağıdaki içerikleri kopyalayıp yapıştırın
# 3. Yeni dosyayı kaydedin (ve GitHub'a gönderin)
# 4. Render'da "Yeni +" > "Mavi Kopya"ya tıklayın
# 5. Kendi çatallı cgm-remote-monitor deponuzu bağlayın
# 6. Gerekli ortam değişkenlerini doldurun
# 7. "Uygula"ya tıklayın ve dağıtımın tamamlanmasını bekleyin.

Hizmetler:
  - tür: web
    isim: nightscout
    env: düğüm
    bölge: oregon # isteğe bağlı (varsayılan oregon'dur. Diğer bölgeler: ohio, frankfurt, singapur)
    plan: ücretsiz # isteğe bağlı (varsayılan olarak ücretsizdir - bu ÜCRETSİZ bir PLAN olabilir... https://render.com/pricing)
    buildCommand: npm kurulum
    startKomutu: npm start
    sağlıkKontrolYolu: /
    envVars:
      - anahtar: INSECURE_USE_HTTP # TLS, uygulamaya ulaşmadan sonlandırılır, bu nedenle yalnızca HTTP'ye yanıt vermesi gerekir.
        değer: doğru
      - anahtar: HOSTNAME # uygulamayı herhangi bir dahili IP'ye bağla
        değer: "0.0.0.0"
      - anahtar: MONGODB_URI # MongoDB kümenize bağlanmak için MongoDB Bağlantı Dizisi. MongoDB Atlas'tan bu yoksa lütfen devam etmeden önce http://nightscout.github.io/nightscout/new_user/ adresindeki kurulum talimatlarını tekrar okuyun
        senkronizasyon: false # Blueprint oluşturulduğunda istenecektir
      - tuşu: ALARM_HIGH # Yeni tarayıcı görünümleri için varsayılan ayar, Yüksek alarmı için (BG, BG_TARGET_TOP'u geçtiğinde tetiklenir). ('açık' veya 'kapalı')
        değer: "açık"
      - tuşu: ALARM_LOW # Yeni tarayıcı görünümleri için varsayılan ayar, Düşük alarmı için (BG, BG_TARGET_BOTTOM'ı geçtiğinde tetiklenir). ('açık' veya 'kapalı')
        değer: "açık"
      - anahtar: ALARM_TIMEAGO_URGENT # Yeni tarayıcı görünümleri için varsayılan ayar, ALARM_TIMEAGO_URGENT_MINS'de ayarlanan dakika sayısı içinde CGM verisi alınmadığında acil bir alarm için. ('açık' veya 'kapalı')
        değer: "açık"
      - anahtar: ALARM_TIMEAGO_URGENT_MINS # Son CGM okumasından bu yana geçen dakika sayısını ALARM_TIMEAGO_URGENT alarmını tetiklemek için yeni tarayıcı görünümleri için varsayılan ayar.
        değer: "30"
      - tuşu: ALARM_TIMEAGO_WARN # Yeni tarayıcı görünümleri için varsayılan ayar, ALARM_TIMEAGO_WARN_MINS'de ayarlanan dakika sayısı içinde CGM verisi alınmadığında bir uyarı alarmı verilmesi. ('açık' veya 'kapalı')
        değer: "açık"
      - anahtar: ALARM_TIMEAGO_WARN_MINS # Son CGM okumasından bu yana geçen dakika sayısını ALARM_TIMEAGO_WARN alarmını tetiklemek için yeni tarayıcı görünümleri için varsayılan ayar.
        değer: "15"
      - anahtar: ALARM_TYPES # 'basit' ve/veya 'tahmin'. Basit alarmlar, BG aşağıda ayarlanan çeşitli eşikleri geçtiğinde tetiklenir. Tahmin alarmları, BG'nin eğilimine göre nereye gittiğini tahmin eden bir formül kullanır. Tahmin türünü kullanırken, aşağıda ayarlanan BG eşiklerini geçtiğinizde uyarı *almazsınız*.
        değer: "basit"
      - tuşu: ALARM_URGENT_HIGH # Yeni tarayıcı görünümleri için varsayılan ayar, Acil Yüksek alarmı için (BG, BG_HIGH'ı geçtiğinde tetiklenir). ('açık' veya 'kapalı')
        değer: "açık"
      - tuşu: ALARM_URGENT_LOW # Yeni tarayıcı görünümleri için varsayılan ayar, Acil Düşük alarmı için (BG, BG_LOW'u geçtiğinde tetiklenir). ('açık' veya 'kapalı')
        değer: "açık"
      - anahtar: API_SECRET # En az 12 karakter uzunluğunda olması gereken bir parola. Bazı durumlarda sorunlara neden olabilecek 'özel' karakterlerden kaçının.
        senkronizasyon: false # Blueprint oluşturulduğunda istenecektir
      - anahtar: BG_HIGH # Acil Yüksek BG eşiği, ALARM_URGENT_HIGH alarmını tetikler. DISPLAY_UNITS değişkeninde ayarlandığı gibi mg/dL veya mmol/L olarak ayarlanır.
        değer: "260"
      - tuşu: BG_LOW # Acil Düşük BG eşiği, ALARM_URGENT_LOW alarmını tetikler. DISPLAY_UNITS değişkeninde ayarlandığı gibi mg/dL veya mmol/L olarak ayarlanır.
        değer: "55"
      - anahtar: BG_TARGET_BOTTOM # Düşük BG eşiği, ALARM_LOW alarmını tetikler. DISPLAY_UNITS değişkeninde ayarlandığı gibi mg/dL veya mmol/L olarak ayarlanır.
        değer: "80"
      - anahtar: BG_TARGET_TOP # Yüksek BG eşiği, ALARM_HIGH alarmını tetikler. DISPLAY_UNITS değişkeninde ayarlandığı gibi mg/dL veya mmol/L olarak ayarlanır.
        değer: "180"
      - anahtar: BOLUS_RENDER_OVER # 'x U ve Üzeri' seçeneği seçildiğinde bolus değerlerinin grafikte işleneceği U değeri.
        değer: "1"
      - key: BRIDGE_PASSWORD # Dexcom Share servisinden CGM verilerini almak için Dexcom hesabınızın şifresi. Ayrıca ENABLE satırınıza 'bridge' eklediğinizden emin olun.
        değer: "şifre"
      - anahtar: BRIDGE_SERVER # Dexcom Share servisinden köprüleme yapıyorsanız ve ABD *dışında* bir yerdeyseniz, bunu AB olarak değiştirin. ('ABD' veya 'AB')
        değer: "AB"
      - anahtar: BRIDGE_USER_NAME # Dexcom Share servisinden CGM verilerini almak için Dexcom hesabınızın kullanıcı adı. Ayrıca ENABLE satırınıza 'bridge' eklediğinizden emin olun.
        değer: "kullanıcı adı"
      - anahtar: CUSTOM_TITLE # Nightscout sitesi için görüntü adı. Ana görünümün sol üst kısmında görünür. Genellikle CGM kullanıcısının adına ayarlanır.
        değer: ""
      - anahtar: DISPLAY_UNITS # Site için tercih edilen BG birimleri: 'mg/dl' veya 'mmol/L' (veya sadece 'mmol').
        senkronizasyon: false # Blueprint oluşturulduğunda istenecektir
      - key: ENABLE # Siteniz için etkinleştirilecek eklentiler. Boşlukla ayrılmış, küçük harfli bir liste olmalıdır. Dexcom Share servisinden veri alıyorsanız buraya 'bridge' kelimesini ekleyin. MiniMed CareLink servisinden köprüleme yapıyorsanız 'mmconnect' kelimesini ekleyin.
        değer: "careportal bazal dbsize rawbg iob maker cob bwp kafes iage sage boluscalc pushover treatmentnotify loop pompa profili yiyecek openaps bage alexa geçersiz kılma konuşma cors"
      - anahtar: NIGHT_MODE # Yeni tarayıcı görünümleri için varsayılan ayar, Gece Modu'nun etkinleştirilip etkinleştirilmeyeceği. ('açık' veya 'kapalı')
        değer: "kapalı"
      - anahtar: SHOW_PLUGINS # Bu eklentilerin varsayılan olarak işaretli (etkin) olup olmayacağına dair varsayılan ayar, yalnızca etkin değil. Eklentileri buraya ENABLE satırında olduğu gibi ekleyin; boşlukla ayrılmış ve küçük harfli.
        değer: "careportal dbize"
      - anahtar: SHOW_RAWBG # Yeni tarayıcı görünümleri için, ham CGM verilerinin görüntülenmesi için varsayılan ayar (varsa). ('her zaman', 'asla' veya 'gürültü')
        değer: "asla"
      - anahtar: TEMA # CGM grafiğinin renk teması için yeni tarayıcı görünümleri için varsayılan ayar. ('varsayılan', 'renkler' veya 'renk körü dostu')
        değer: "renkler"
      - anahtar: TIME_FORMAT # Yeni tarayıcı görünümleri için varsayılan ayar, zaman modu için. ('12' veya '24')
        değer: "12"
